[platformio]
src_dir = .
default_envs = wristband, plush

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:wristband]
build_src_filter = +<wristband/>

[env:plush]
build_src_filter = +<plush/>
lib_deps = madhephaestus/ESP32Servo
